#
# SFU CMPT 756.211
#
# This manifest is used to push your AWS credentials via k8s secret into
# your cluster for consumption by the db service.
#
# You will need to put the AWS credentials here regardless of whether
# you are running your cluster on AWS, Minikube, Azure, GCP, or anywhere
# else. No matter where you run, you will be calling AWS DynamoDB as
# your database.
#
apiVersion: v1
kind: Secret
metadata:
  name: awscred
type: Opaque
stringData:
  # If you are running DynamoDB from an AWS starter ID, you must specify us-east-1
  # as your region.  If you are running from a regular AWS ID, you may specify
  # any region.  us-west-2 is the AWS region closest to Vancouver and therefore
  # will have the lowest geolatency.
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: AKIATFWMJ6OVPRDODUMY
  AWS_SECRET_ACCESS_KEY: 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
